// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANjnVjPrc6Yz1NCSNeKik0avk8oIDfWak',
    appId: '1:675301500605:web:38320baee823ce0ab1b9d4',
    messagingSenderId: '675301500605',
    projectId: 'mathq-3bcc8',
    authDomain: 'mathq-3bcc8.firebaseapp.com',
    storageBucket: 'mathq-3bcc8.appspot.com',
    measurementId: 'G-YKY2VCSHH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCABzRQ1_QW4_k4FobxK60fJhNxAQeHYg',
    appId: '1:675301500605:android:23ff667ae216b596b1b9d4',
    messagingSenderId: '675301500605',
    projectId: 'mathq-3bcc8',
    storageBucket: 'mathq-3bcc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB0wCTbgDrOHgCyuLzdADO5h-amdx7kQI',
    appId: '1:675301500605:ios:ea1c9b0397ff6d6ab1b9d4',
    messagingSenderId: '675301500605',
    projectId: 'mathq-3bcc8',
    storageBucket: 'mathq-3bcc8.appspot.com',
    iosBundleId: 'com.example.mathq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB0wCTbgDrOHgCyuLzdADO5h-amdx7kQI',
    appId: '1:675301500605:ios:abbdfbacc83951d5b1b9d4',
    messagingSenderId: '675301500605',
    projectId: 'mathq-3bcc8',
    storageBucket: 'mathq-3bcc8.appspot.com',
    iosBundleId: 'com.example.mathq.RunnerTests',
  );
}
